projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "https://www.palazar.com/"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
